# Generated by Django 2.1.4 on 2018-12-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181101_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_alpha_tester',
            field=models.BooleanField(default=False),
        ),
    ]
