# Generated by Django 3.1.2 on 2020-10-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201024_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commenta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
