# Generated by Django 2.1.4 on 2018-12-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='platform',
            field=models.CharField(choices=[('PC', 'PC'), ('PS4', 'Playstation 4'), ('XB1', 'Xbox One'), ('NSW', 'Nintendo Switch')], default='F', max_length=3),
        ),
    ]
