# Generated by Django 3.1.2 on 2020-10-28 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201024_0045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commenta',
        ),
    ]
