# Generated by Django 2.1.4 on 2018-12-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181212_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='user/avatar/default.png', upload_to='user/avatar'),
        ),
    ]
