# Generated by Django 2.1 on 2018-08-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
