# Generated by Django 2.1 on 2018-08-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20180820_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(blank=True, choices=[('P', 'Peculiar'), ('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('L', 'Legendary'), ('I', 'Riven')], max_length=1),
        ),
    ]
