# Generated by Django 2.1 on 2018-08-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20180820_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ducats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
