# Generated by Django 2.1 on 2018-08-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20180820_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='main',
        ),
    ]
