# Generated by Django 2.1 on 2018-08-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_remove_item_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Item'),
        ),
    ]
