# Generated by Django 2.1 on 2018-08-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20180825_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ended',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='order',
            name='is_ended',
            field=models.BooleanField(null=True),
        ),
    ]
