# Generated by Django 2.1 on 2018-08-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20180826_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='mastery_level',
            new_name='mastery_rank',
        ),
    ]
