# Generated by Django 2.1 on 2018-08-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20180827_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='main',
            new_name='parent',
        ),
    ]
