# Generated by Django 2.1 on 2018-08-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_auto_20180829_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='want',
            field=models.CharField(choices=[('S', 'Sell'), ('B', 'Buy')], default='S', max_length=1),
        ),
    ]
