# Generated by Django 2.1.4 on 2018-12-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0065_companion_release_date'),
        ('market', '0020_auto_20181226_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='companion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.Companion'),
        ),
        migrations.AddField(
            model_name='item',
            name='warframe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.Warframe'),
        ),
        migrations.AddField(
            model_name='item',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.Weapon'),
        ),
    ]
