# Generated by Django 2.1.4 on 2018-12-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_auto_20181226_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tipe',
            field=models.CharField(choices=[('C', 'Companion'), ('M', 'Mods'), ('W', 'Warframe'), ('E', 'Weapon')], default='E', max_length=1),
        ),
    ]
