# Generated by Django 2.1.4 on 2018-12-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_item_tipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
