# Generated by Django 2.1.4 on 2018-12-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_auto_20181226_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='a'),
        ),
    ]
