# Generated by Django 2.1.4 on 2018-12-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(),
        ),
    ]
