# Generated by Django 2.1.4 on 2018-12-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_auto_20181226_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
