# Generated by Django 2.1.4 on 2019-01-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_remove_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='companion',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tipe',
        ),
        migrations.RemoveField(
            model_name='item',
            name='warframe',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weapon',
        ),
    ]
