# Generated by Django 2.1.4 on 2019-01-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_auto_20190102_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
