# Generated by Django 2.1.4 on 2019-01-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_auto_20190102_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mod_rank',
        ),
    ]
