# Generated by Django 2.1.4 on 2019-01-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_orderbeast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeast',
            name='image',
            field=models.ImageField(upload_to='market/order/beast'),
        ),
    ]
