# Generated by Django 2.1.4 on 2019-01-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_auto_20190104_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, upload_to='market/order/'),
        ),
    ]
