# Generated by Django 2.1.4 on 2019-01-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(default='market/order/default.png', upload_to='market/order/'),
        ),
    ]
