# Generated by Django 2.1 on 2018-08-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, default='codex/quests/default.png', upload_to='codex/quests')),
            ],
        ),
    ]
