# Generated by Django 2.1.4 on 2019-01-18 20:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=700)),
                ('image', models.ImageField(blank=True, default='codex/item/default.png', upload_to='codex/item')),
                ('mastery_rank', models.PositiveIntegerField(default=0)),
                ('is_prime', models.BooleanField(default=False)),
                ('is_tradeable', models.BooleanField(default=False)),
                ('release_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemAbilityValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=210)),
                ('image', models.ImageField(blank=True, default='codex/item/ability/default.png', upload_to='codex/item/ability')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.ItemAbility')),
            ],
            options={
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.ItemAttribute')),
            ],
            options={
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='ItemTipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('tipe', models.CharField(choices=[('M', 'Main Quest'), ('O', 'Optional Quest'), ('L', 'Optional Lore Quest')], default='M', max_length=1)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='codex/quests/default.png', upload_to='codex/quests')),
                ('slug', models.SlugField()),
                ('quest_order', models.PositiveIntegerField(blank=True, null=True)),
                ('is_replayable', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('next_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nxt_quest', to='codex.Quest')),
                ('previous_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prv_quest', to='codex.Quest')),
            ],
            options={
                'ordering': ['quest_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestWalkthrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', ckeditor.fields.RichTextField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Quest')),
            ],
            options={
                'ordering': ['-quest'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.ItemTipe'),
        ),
    ]
