# Generated by Django 2.1.4 on 2019-01-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemability',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemabilityvalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemattribute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemattributevalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemtipe',
            options={},
        ),
    ]
