# Generated by Django 2.1 on 2018-08-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quests',
            new_name='Quest',
        ),
    ]
