# Generated by Django 2.1 on 2018-08-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_auto_20180830_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
