# Generated by Django 2.1.4 on 2019-01-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_auto_20190119_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='next_quest',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='previous_quest',
        ),
    ]
