# Generated by Django 2.1.4 on 2019-01-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_auto_20190121_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemabilityvalue',
            name='value',
            field=models.TextField(max_length=320),
        ),
    ]
