# Generated by Django 2.1 on 2018-08-31 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0004_auto_20180830_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
