# Generated by Django 2.1.4 on 2019-01-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0004_auto_20190122_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemabilityvalue',
            name='value',
            field=models.TextField(max_length=360),
        ),
    ]
