# Generated by Django 2.1 on 2018-08-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0005_auto_20180831_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='overview',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='tipe',
            field=models.CharField(choices=[('M', 'Main Quest'), ('O', 'Optional Quest'), ('L', 'Optional Lore Quest')], default='M', max_length=1),
        ),
    ]
