# Generated by Django 2.1 on 2018-09-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0007_auto_20180831_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='overview',
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
