# Generated by Django 2.1 on 2018-09-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0009_auto_20180901_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(default='Description in progress...'),
        ),
    ]
