# Generated by Django 2.1 on 2018-09-01 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0011_auto_20180901_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='next_quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nxt_quest', to='codex.Quest'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='previous_quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prv_quest', to='codex.Quest'),
        ),
    ]
