# Generated by Django 2.1 on 2018-09-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0014_questwalkthrough'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('Au', 'Auto'), ('Ai', 'Air Burst'), ('Ba', 'Barrage'), ('Be', 'Beacon'), ('Bu', 'Buckshot'), ('Bu', 'Burst'), ('Br', 'Burst Shot'), ('Ca', 'Cannon'), ('Ch', 'Charge'), ('Cr', 'Charged Throw'), ('Di', 'Disc'), ('El', 'Electric Quill'), ('Fi', 'Fire Quill'), ('Ha', 'Harpoon'), ('Ho', 'Horizontal Spread'), ('Ic', 'Ice Quill'), ('Me', 'Melee'), ('Po', 'Poison Quill'), ('Pr', 'Primary'), ('Se', 'Secondary'), ('Sm', 'Semi'), ('Sl', 'Slug'), ('Th', 'Throw'), ('Ve', 'Vertical Spread')], default='Pr', max_length=2)),
                ('accuracy', models.DecimalField(decimal_places=1, max_digits=4)),
                ('charge_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fire_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('magazine', models.PositiveIntegerField()),
                ('noise', models.BooleanField()),
                ('punch_through', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rload', models.DecimalField(decimal_places=1, max_digits=2)),
                ('trigger', models.CharField(choices=[('', 'Auto'), ('', 'Burst'), ('', 'Charge'), ('', 'Held'), ('', 'Semi')], default='A', max_length=1)),
                ('attack_speed', models.DecimalField(decimal_places=3, max_digits=4)),
                ('channeling_cost', models.PositiveIntegerField()),
                ('channeling_damage', models.DecimalField(decimal_places=1, max_digits=2)),
                ('damage_block', models.DecimalField(decimal_places=1, max_digits=4)),
                ('leap_attack', models.DecimalField(decimal_places=1, max_digits=4)),
                ('spin_attack', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wall_attack', models.DecimalField(decimal_places=1, max_digits=4)),
                ('critical_chance', models.DecimalField(decimal_places=1, max_digits=4)),
                ('critical_multiplier', models.DecimalField(decimal_places=1, max_digits=2)),
                ('status', models.DecimalField(decimal_places=1, max_digits=4)),
                ('impact', models.DecimalField(decimal_places=1, max_digits=5)),
                ('puncture', models.DecimalField(decimal_places=1, max_digits=5)),
                ('slash', models.DecimalField(decimal_places=1, max_digits=5)),
                ('cold', models.DecimalField(decimal_places=1, max_digits=5)),
                ('electricity', models.DecimalField(decimal_places=1, max_digits=5)),
                ('heat', models.DecimalField(decimal_places=1, max_digits=5)),
                ('toxin', models.DecimalField(decimal_places=1, max_digits=5)),
                ('void', models.DecimalField(decimal_places=1, max_digits=5)),
                ('blast', models.DecimalField(decimal_places=1, max_digits=5)),
                ('corrosive', models.DecimalField(decimal_places=1, max_digits=5)),
                ('gas', models.DecimalField(decimal_places=1, max_digits=5)),
                ('magnetic', models.DecimalField(decimal_places=1, max_digits=5)),
                ('radiation', models.DecimalField(decimal_places=1, max_digits=5)),
                ('viral', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, default='weapons/default.png', upload_to='weapons')),
                ('tipe', models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('M', 'Melee')], default='P', max_length=1)),
                ('description', models.TextField(max_length=600)),
                ('mastery_rank', models.PositiveIntegerField()),
            ],
        ),
    ]
