# Generated by Django 2.1 on 2018-09-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0016_auto_20180906_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='mastery_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
