# Generated by Django 2.1 on 2018-09-06 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0018_weapon_is_tradeable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='is_tradeable',
        ),
        migrations.AddField(
            model_name='weapon',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
