# Generated by Django 2.1 on 2018-09-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0020_auto_20180906_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='trigger',
            field=models.CharField(choices=[('A', 'Auto'), ('B', 'Burst'), ('C', 'Charge'), ('H', 'Held'), ('S', 'Semi')], default='A', max_length=1),
        ),
    ]
