# Generated by Django 2.1 on 2018-09-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0023_auto_20180910_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='noise',
            field=models.BooleanField(),
        ),
    ]
