# Generated by Django 2.1 on 2018-09-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0024_auto_20180910_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['tipe']},
        ),
        migrations.AddField(
            model_name='quest',
            name='order_by',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='trigger',
            field=models.CharField(blank=True, choices=[('A', 'Auto'), ('B', 'Burst'), ('C', 'Charge'), ('H', 'Held'), ('S', 'Semi')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='tipe',
            field=models.CharField(choices=[('P', 'Primary Weapon'), ('S', 'Secondary Weapon'), ('M', 'Melee Weapon')], default='P', max_length=1),
        ),
    ]
