# Generated by Django 2.1 on 2018-09-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0025_auto_20180911_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='quest',
            name='order_by',
        ),
    ]
