# Generated by Django 2.1 on 2018-09-12 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0027_auto_20180911_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={},
        ),
    ]
