# Generated by Django 2.1 on 2018-09-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0029_auto_20180912_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={},
        ),
        migrations.AlterField(
            model_name='questwalkthrough',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Quest'),
        ),
    ]
