# Generated by Django 2.1 on 2018-09-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0030_auto_20180912_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questwalkthrough',
            name='description',
            field=models.TextField(),
        ),
    ]
