# Generated by Django 2.1 on 2018-09-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0031_auto_20180912_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(),
        ),
    ]
