# Generated by Django 2.1 on 2018-11-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0035_auto_20181124_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='tipe',
            field=models.CharField(choices=[('Ac', 'Active'), ('Au', 'Auto'), ('Ai', 'Air Burst'), ('Ba', 'Barrage'), ('Be', 'Beacon'), ('Bu', 'Buckshot'), ('Br', 'Burst'), ('Bs', 'Burst Shot'), ('Ca', 'Cannon'), ('Ch', 'Charge'), ('Cr', 'Charged Throw'), ('Di', 'Disc'), ('El', 'Electric Quill'), ('Fi', 'Fire Quill'), ('Ha', 'Harpoon'), ('Ho', 'Horizontal Spread'), ('Ic', 'Ice Quill'), ('Me', 'Melee'), ('Po', 'Poison Quill'), ('Pr', 'Primary'), ('Se', 'Secondary'), ('Sm', 'Semi'), ('Sl', 'Slug'), ('Th', 'Throw'), ('Ve', 'Vertical Spread')], default='Pr', max_length=2),
        ),
        migrations.AlterField(
            model_name='stat',
            name='trigger',
            field=models.CharField(blank=True, choices=[('A', 'Auto'), ('B', 'Burst'), ('C', 'Charge'), ('D', 'Duplex'), ('H', 'Held'), ('S', 'Semi')], max_length=1, null=True),
        ),
    ]
