# Generated by Django 2.1.4 on 2018-12-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0038_auto_20181205_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['weapon']},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['name']},
        ),
    ]
