# Generated by Django 2.1.4 on 2018-12-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0040_auto_20181206_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='next_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nxt_quest', to='codex.Quest'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='previous_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prv_quest', to='codex.Quest'),
        ),
    ]
