# Generated by Django 2.1.4 on 2018-12-11 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0041_auto_20181207_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=280)),
                ('pasive', models.TextField(max_length=140)),
                ('armor', models.PositiveIntegerField()),
                ('energy', models.PositiveIntegerField()),
                ('health', models.PositiveIntegerField()),
                ('shield', models.PositiveIntegerField()),
                ('sprint_speed', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='WarframeAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=140)),
                ('image', models.ImageField(blank=True, default='codex/warframe/ability/default.png', upload_to='codex/warframe/ability')),
                ('pasive', models.TextField(max_length=140)),
                ('warframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Warframe')),
            ],
        ),
    ]
