# Generated by Django 2.1.4 on 2018-12-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0042_warframe_warframeability'),
    ]

    operations = [
        migrations.AddField(
            model_name='warframe',
            name='image',
            field=models.ImageField(blank=True, default='codex/warframe/default.png', upload_to='codex/warframe'),
        ),
    ]
