# Generated by Django 2.1.4 on 2018-12-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0044_warframe_is_prime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questwalkthrough',
            options={'ordering': ['quest']},
        ),
        migrations.AlterModelOptions(
            name='warframe',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='warframeability',
            options={'ordering': ['warframe']},
        ),
        migrations.AlterField(
            model_name='warframe',
            name='pasive',
            field=models.TextField(max_length=280),
        ),
    ]
