# Generated by Django 2.1.4 on 2018-12-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0045_auto_20181211_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='warframe',
            name='mastery_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
