# Generated by Django 2.1.4 on 2018-12-12 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0046_warframe_mastery_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='warframe',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warframe',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warframeability',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warframeability',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
