# Generated by Django 2.1.4 on 2018-12-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0048_remove_warframeability_pasive'),
    ]

    operations = [
        migrations.AddField(
            model_name='warframe',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
