# Generated by Django 2.1.4 on 2018-12-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0050_auto_20181212_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='warframe',
            name='is_tradeable',
            field=models.BooleanField(default=False),
        ),
    ]
