# Generated by Django 2.1.4 on 2018-12-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0051_warframe_is_tradeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='quest_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
