# Generated by Django 2.1.4 on 2018-12-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0052_quest_quest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
