# Generated by Django 2.1.4 on 2018-12-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0053_weapon_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
