# Generated by Django 2.1.4 on 2018-12-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0054_quest_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['quest_order']},
        ),
        migrations.RemoveField(
            model_name='quest',
            name='release_date',
        ),
    ]
