# Generated by Django 2.1.4 on 2018-12-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0055_auto_20181213_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='warframe',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
