# Generated by Django 2.1.4 on 2018-12-14 15:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0056_warframe_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questwalkthrough',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
