# Generated by Django 2.1.4 on 2018-12-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0057_auto_20181214_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=280)),
                ('armor', models.PositiveIntegerField(blank=True, null=True)),
                ('health', models.PositiveIntegerField(blank=True, null=True)),
                ('shield', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='questwalkthrough',
            options={'ordering': ['-quest']},
        ),
    ]
