# Generated by Django 2.1.4 on 2018-12-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0058_auto_20181221_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companion',
            name='is_tradeable',
            field=models.BooleanField(default=False),
        ),
    ]
