# Generated by Django 2.1.4 on 2018-12-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0059_auto_20181221_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='image',
            field=models.ImageField(blank=True, default='codex/companion/default.png', upload_to='codex/companion'),
        ),
    ]
