# Generated by Django 2.1.4 on 2018-12-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0061_companion_tipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companion',
            options={'ordering': ['name']},
        ),
    ]
