# Generated by Django 2.1.4 on 2018-12-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0062_auto_20181221_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='mastery_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
