# Generated by Django 2.1.4 on 2018-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0063_companion_mastery_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
