# Generated by Django 2.1.4 on 2018-12-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0064_auto_20181221_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
