# Generated by Django 2.1.4 on 2018-12-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0065_companion_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
    ]
