# Generated by Django 2.1.4 on 2018-12-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0066_weapon_is_prime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=700)),
                ('image', models.ImageField(blank=True, default='codex/quests/default.png', upload_to='codex/quests')),
                ('is_prime', models.BooleanField(default=False)),
                ('is_tradeable', models.BooleanField(default=False)),
            ],
        ),
    ]
