# Generated by Django 2.1.4 on 2018-12-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0068_itemtipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtipe',
            old_name='item',
            new_name='tipe',
        ),
    ]
