# Generated by Django 2.1.4 on 2019-01-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0072_auto_20181231_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itemattribute',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itemtipe',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='codex/items/default.png', upload_to='codex/items/'),
        ),
    ]
