# Generated by Django 2.1.4 on 2019-01-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0073_auto_20190102_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttributeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=280)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.ItemAttribute')),
            ],
        ),
    ]
