# Generated by Django 2.1.4 on 2019-01-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0074_itemattributetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemattributetext',
            name='value',
            field=models.TextField(max_length=180),
        ),
    ]
