# Generated by Django 2.1.4 on 2019-01-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0075_auto_20190102_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemAbilityValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=180)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.Item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.ItemAbility')),
            ],
        ),
    ]
