# Generated by Django 2.1.4 on 2019-01-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0077_itemability_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattributetext',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemattributetext',
            name='name',
        ),
        migrations.DeleteModel(
            name='ItemAttributeText',
        ),
    ]
