# Generated by Django 2.1.4 on 2019-01-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0078_auto_20190102_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='codex/item/default.png', upload_to='codex/item'),
        ),
        migrations.AlterField(
            model_name='itemability',
            name='image',
            field=models.ImageField(blank=True, default='codex/item/ability/default.png', upload_to='codex/item/ability'),
        ),
    ]
