# Generated by Django 2.1.4 on 2019-01-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0079_auto_20190102_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemability',
            name='image',
        ),
        migrations.AddField(
            model_name='itemabilityvalue',
            name='image',
            field=models.ImageField(blank=True, default='codex/item/ability/default.png', upload_to='codex/item/ability'),
        ),
    ]
