# Generated by Django 2.1.4 on 2019-01-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0080_auto_20190102_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companion',
        ),
    ]
