# Generated by Django 2.1.4 on 2019-01-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0081_delete_companion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warframeability',
            name='warframe',
        ),
        migrations.DeleteModel(
            name='WarframeAbility',
        ),
    ]
