# Generated by Django 2.1.4 on 2019-01-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0083_auto_20190108_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warframe',
        ),
        migrations.AlterModelOptions(
            name='itemabilityvalue',
            options={'ordering': ['item']},
        ),
        migrations.AlterModelOptions(
            name='itemattributevalue',
            options={'ordering': ['-item']},
        ),
    ]
